export const initialUserFormState = {
  type: null,
  role: null,
  full_name: null,
  email: null,
  password: null,
  confirmPassword: null,
  description: null,
  discount: null,
  address: null,
  city: null,
  phone: null,
  is_rehab_employee: null,
  is_rehab_admin: null,
  rehab: null,
  is_super_admin: null,
  availability: null,
  details: null,
  dob: null,
  education: null,
  experience: null,
  gender: null,
  hospital: null,
  emergency: null,
  perHour: null,
  perDay: null,
  images: [],
  lat: null,
  long: null,
  // ref: null,
  // rgNo: null,
  speciality: null,
  unAvailability: null
};

export const initialBookingFormState = {
  booking_type: null,
  requested_user_id: null,
  booked_by: null,
  requested_rehab_id: null,
  is_booked_rehab: null,
  appointment_date: null,
  rate_type: "perHour",
  from: null,
  to: null,
  start_date: null,
  end_date: null,
  package: "perDay",
  reason_for_booking: null,
  booking_Desc: null,
  amount: null,
  patientName: null,
  gender: "male",
  message: null,
  phone: null,
  alternative_phone: null,
  DOB: null,
  rate: null,
  ref: null,
  payment_status: null,
  status: null,
  type: null,
  start_time: null,
  end_time: null,
}